build:
  script:
    - apt update -y
    - apt install python3 -y
    - apt install python3-venv -y
    - mkdir -p /builds/cicd-groups/flaskapplication-cicd/flask_env  # Ensure the directory exists
    - python3 -m venv /builds/cicd-groups/flaskapplication-cicd/flask_env
    - source /builds/cicd-groups/flaskapplication-cicd/flask_env/bin/activate
    - pip3 install --upgrade pip

deploy:
  script:
    - apt update -y
    - flask --app main.py run