build:
  script:
    - export PYTHONPATH=.
    - export FLASK_APP=web
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip3 install Flask

deploy:
  script:
    - apt update -y
    - flask --app main.py run