stages:
  - build_stage
  - deploy_stage

build:
  stage: build_stage
  script:
    - docker --version
    - docker build --tag python-docker .
  tags:
    - flask-server
    - ubuntu
    

deploy:
  stage: deploy_stage
  script:
    - docker run -d -p 5000:5000 python-docker
  tags:
    - flask-server
    - ubuntu