build:
  script:
    - apt update -y
    - apt install python3 -y
    - apt install python3-venv -y
    - python3 -m venv flask_env
    - pip3 install flask

deploy:
  script:
    - apt update -y
    - flask --app main.py run